### ISSUE TITLE
Curve OP2 DEX Duplication

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/abstractions#1073]
re: https://github.com/duneanalytics/abstractions/pull/1069

Hi, it seems like Curve trades are still duplicated in optimism2 dex.trades for May 20 UTC. 

Was this and edge case in delete / re-insert after the update or is something still being duplicated?

**Comment by jeff-dude** [comment]
hi @MSilb7 i don't see the duplicates? based on dex trades table definition & 'ON CONFLICT' statement in curve function, this query here should be unique and i'm seeing it as true. no rows returned.
```
select
  project,
  tx_hash,
  evt_index,
  trade_id,
  count(1)
from
  dex.trades
where
  project = 'Curve'
group by
  project,
  tx_hash,
  evt_index,
  trade_id
having
  count(1) > 1
order by
  5 desc
```

**Comment by MSilb7** [comment]
When I run the local version of the insert query here, I only get ~19k https://dune.com/queries/830261

But in dex.trdaes, there's 2.2M on May 20: https://dune.com/queries/852860

I'll check again if there are any diffs vs the insert

**Comment by MSilb7** [comment]
Just tested and not seeing any duplication with the insert query as-is.

I think some extra data got inserted between deleting the old Curve trades and re-doing the insert query.

Example tx hash: `\x54f23f47d4bcd19d0982962df8d96d0c632df0fa0ee248eb62d34fbcb679b62b` - https://optimistic.etherscan.io/tx/0x54f23f47d4bcd19d0982962df8d96d0c632df0fa0ee248eb62d34fbcb679b62b

**Comment by MSilb7** [comment]
Hi, re-bumping here

**Comment by jeff-dude** [comment]
some strange behavior is happening. when i run the query in the web app, results are as expected -- similar to what you found above. when i run the function to load >= 5/19/22 (after deleting), it claims to load 12,949 rows. when i query dex trades after, it explodes to that 2.2mil number again.

**Comment by jeff-dude** [comment]
okay, i think i have it fixed. in line 69, i added a 'DISTINCT' after the select for rows to go into the insert statement. i wonder if the web app detected that for us but postgres didn't? i can try to ask the team, see if something is going on there. can you do me a favor and submit a new simple PR which adds that distinct? then i can merge it in. it's already applied in the db and cron is enabled again, but want to get the repo up-to-date

**Comment by MSilb7** [comment]
Yeah will do. Definitely weird haha

**Comment by MSilb7** [comment]
https://github.com/duneanalytics/abstractions/pull/1116

**Comment by jeff-dude** [comment]
closing with latest linked PR. let's hope that cleans it up!
