### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by LuozhuZhang** [duneanalytics/abstractions#1075]
👋 I like dune very much. And I was an on-chain data scientist(mostly built an on-chian data ETL), now join scroll to build zkEVM with ethereum foundation.

And I want to give some feedback to make dune batter:

1) I think dune is a great on-chain data infrastructure, but it is more like a web2 App, not a web3 protocol. I belive the team will lead dune to a right path, so I suggest dune consider build a more basic infra/protocol which can permit other on-chain data projects live on the dune.  (like build a nansen on dune)

2) I think dune more like on-chain data Github, so why not add an organization feature. Dune should help build a home for a data developers.

3) Will onboard many new users!! For now, most users are investors. But now I was creating a zkEVM dashboard for engineers more understand call data size or trace input/output stuff. So many dever will be the users of dune in the FUTURE. Happy to see that.

If u need any help, or u want to make a quick call to know more detail. Pls feel free to DM me

**Comment by LuozhuZhang** [comment]
Most exciting ideas: build a nansen on dune, build a "the graph" on dune.
Just like the relationship between Dapps and ethereum network.

**Comment by mewwts** [comment]
Thanks for your ideas @LuozhuZhang!

You'll see some exciting news soon :)

**Comment by LuozhuZhang** [comment]
> Thanks for your ideas @LuozhuZhang!
> 
> You'll see some exciting news soon :)

Already looking forward to it :)
