### ISSUE TITLE
ERC20 Transfer Duplication in V2

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/abstractions#1120]
In the V2 Engine, I noticed a transaction where the ERC20 Transfer log was duplicated:

`0xda236cd264b5ca658a7f534a87da124aeafdc2de77846b5a5e13f184012b3712` shows evt_index 171 twice, creating duplicate rows.

Compared vs Etherscan, where there's one transfer event: https://etherscan.io/tx/0xda236cd264b5ca658a7f534a87da124aeafdc2de77846b5a5e13f184012b3712#eventlog
![image](https://user-images.githubusercontent.com/4006780/171798038-7c094a0f-8e20-48ab-8317-2cabb22e52b7.png)

**Comment by dot2dotseurat** [comment]
Heads up, I am looking into this. I am seeing 8132 rows that are duplicates in this table. I will report back when I get to the bottom of it. 

We are using a slight reworking on this table internally called `transfers_ethereum.erc20`. I can surface a version without any duplicated events and work with our platform team on finding the root cause. 

```(abstractions) (base) ➜  spellbook git:(issue-1120-duplicates-erc20-transfers) ✗ dbt test --select source:erc20_ethereum.evt_transfer
17:45:44  Running with dbt=1.0.4
17:45:44  Unable to do partial parsing because profile has changed
17:45:45  Found 41 models, 25 tests, 0 snapshots, 0 analyses, 215 macros, 0 operations, 8 seed files, 17 sources, 0 exposures, 0 metrics
17:45:45  
17:49:09  Concurrency: 1 threads (target='dev')
17:49:09  
17:49:09  1 of 1 START test source_unique_erc20_ethereum_evt_transfer_evt_index........... [RUN]
17:49:42  1 of 1 FAIL 8132 source_unique_erc20_ethereum_evt_transfer_evt_index............ [FAIL 8132 in 32.67s]
17:49:42  
17:49:42  Finished running 1 test in 237.43s.
17:49:42  
17:49:42  Completed with 1 error and 0 warnings:
17:49:42  
17:49:42  Failure in test source_unique_erc20_ethereum_evt_transfer_evt_index (models/base_sources/ethereum_base_sources.yml)
17:49:42    Got 8132 results, configured to fail if != 0
17:49:42  
17:49:42    compiled SQL at target/compiled/spellbook/models/base_sources/ethereum_base_sources.yml/source_unique_erc20_ethereum_evt_transfer_evt_index.sql
17:49:42  
17:49:42  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

**Comment by MSilb7** [comment]
Saw the new PR, awesome! Definitely a weird one.

Do you all want me to mark this as resolved, or leave it open until the other upstream processing issue mentioned in the PR is resolved?
