### ISSUE TITLE
Let's make list of table hierarchical?

### ISSUE THREAD

**Issue by k06a** [duneanalytics/abstractions#1124]
Let me know what do you think regarding making this list nested:

<img width="326" alt="image" src="https://user-images.githubusercontent.com/702124/172067854-2a986366-e52b-4a6a-8d77-bc6a75ecebf3.png">

**Comment by dot2dotseurat** [comment]
This looks like it's from the V1 engine/data explorer. Check out what it looks like on V2.

<img width="417" alt="Screen Shot 2022-07-22 at 5 09 25 PM" src="https://user-images.githubusercontent.com/9472574/180569008-28b8e187-dbd8-4eb2-8b5d-d6d637d9ad7d.png">
<img width="413" alt="Screen Shot 2022-07-22 at 5 09 32 PM" src="https://user-images.githubusercontent.com/9472574/180569015-bb901d05-47c1-4925-af99-f6953b6487a2.png">

**Comment by k06a** [comment]
Thanks @dot2dotseurat, that’s exactly what I asked for :)
