### ISSUE TITLE
rarible_v1 no Data after Contract switch

### ISSUE THREAD

**Issue by dArkjON** [duneanalytics/abstractions#117]
Hi Guys,
the rarible_v1 wont work after the 03/09 because the owner released a new contract.

rarible_v1."ERC721Sale_v1_evt_Buy" & rarible_v1."ERC1155Sale_v1_evt_Buy" are affected.

old contracts  : 0x8c530a698b6e83d562db09079bc458d4dad4e6c5 & 0xA5aF48b105Ddf2fa73cBaaC61d420eA31b3c2a07 
new contracts : 0x93f2a75d771628856f37f256da95e99ea28aafbe & 0x131aebbfe55bca0c9eaad4ea24d386c5c082dd58

I hope this is enough info to fix it 😎 

Greetings ✌️

**Comment by mewwts** [comment]
Thanks @dArkjON! We'll add these shortly. In the future you can add using duneanalytics.com/decode if you want to add more contracts!
