### ISSUE TITLE
Schema : rarible_v1.ERC1155Sale_v2_evt_Buy - Column : tokenId

### ISSUE THREAD

**Issue by dArkjON** [duneanalytics/abstractions#121]
Hey Guys,
thanks for the fast update and solving Issue #117 😎 👍 

This issue is for the new schema : rarible_v1.ERC1155Sale_v2_evt_Buy

I tried to parse a specific token on the Column "tokenId" but i get the same Error anytime...
This is my Query to test it :

> SELECT tokenId
> FROM rarible_v1."ERC721Sale_v1_evt_Buy"
> GROUP BY tokenId

The Error message i get is :
> Error running query: column "tokenid" does not exist LINE 1: ...ery Hash: 088b80fbe2b501ac75abf8cdbe67ec38 */ SELECT tokenId ^ HINT: Perhaps you meant to reference the column "ERC721Sale_v1_evt_Buy.tokenId".

It looks like the script try to gather Info from "tokenid" instead of "tokenId" but im not sure🤷‍♂️

Greetings
Jon

**Comment by mewwts** [comment]
Hey Jon,

Using double quotes around the column would solve this `"tokenId"`

Feel free to join our telegram group at https://t.me/dunefriends to ask questions like these :)

**Comment by darrianussery7** [comment]
Fallow throught
