### ISSUE TITLE
add DHT

### ISSUE THREAD

**Issue by cmagan** [duneanalytics/abstractions#126]
sorry for the mess (:
couldn't figure out the format for adding a token to the list (spaces vs tabs didn't worked... ):
I just want to add
\\xca1207647Ff814039530D7d35df0e1Dd2e91Fa84 DHT     18

**Comment by mewwts** [comment]
Don't worry, added it now https://github.com/duneanalytics/abstractions/commit/9e8f0ce3641c5da68bd1cc6da4b9912e192daaa7 ;)
