### ISSUE TITLE
Hey, would like to add new tokens

### ISSUE THREAD

**Issue by cmagan** [duneanalytics/abstractions#130]
ticker: GIV 
contract address: 0xf6537fe0df7f0cc0985cf00792cc98249e73efa0
decimals: 8

ticker: FUSE
contract address: 0x970B9bB2C0444F5E81e9d0eFb84C8ccdcdcAf84d
decimals: 18

ticker: ALN
contract address: 0x1b7b723e66a0dd33e8f5e8ec039b51acafcd66a5
decimals: 18

**Comment by mewwts** [comment]
Done thanks :+1:
