### ISSUE TITLE
historical prices missing from dex.view_token_prices when erc20.decimals is added at a later point

### ISSUE THREAD

**Issue by jorijnsmit** [duneanalytics/abstractions#410]
When a token is not known from inception of a dex pool, `erc20.decimals` is not known and `dex.trades.token_a_amount` (or `token_b_amount`) cannot be calculated, resulting in `NULL`.

Problem is that when the token decimals are added at a later date, due to using `INSERT`, `token_a_amount` is never recalculated for the older rows.

https://github.com/duneanalytics/abstractions/blob/e2b1a66bcc5d021d9ac807085aaa79d8c669a9a6/ethereum/dex/trades/insert_sushi.sql#L6

This in turn influences `dex.view_token_prices` since it depends and filters on this column
https://github.com/duneanalytics/abstractions/blob/e2b1a66bcc5d021d9ac807085aaa79d8c669a9a6/ethereum/dex/view_token_prices.sql#L19

Due to this, a lot of price history is not present in `dex.view_token_prices` even though it can be calculated quite easily.

Is there any way to rebuild some of the price tables from scratch, using the now known decimals?

An easy use case is oBTC. Compare for example

```
SELECT *
FROM dex.trades
WHERE token_a_address = '\x8064d9Ae6cDf087b1bcd5BDf3531bD5d8C537a68'
ORDER BY 1 DESC
```
with
```
SELECT *
FROM dex.view_token_prices 
WHERE contract_address = '\x8064d9Ae6cDf087b1bcd5BDf3531bD5d8C537a68'
```
Redefining `token_a_symbol` and `token_a_amount` would be all that's needed.

**Comment by jorijnsmit** [comment]
OK so one solution is to join on `erc20` in the `view_token_prices`, I think this actually makes more sense. However, I don't know what other queries depend on `token_a_amount`. I'm writing a PR which should keep the original columns intact but increase historical price points.

**Comment by bh2smith** [comment]
I think it would also be completely reasonable to include the decimals column directly on this this view instead of having to join. If prices are known, this must also mean that decimals are known.

**Comment by masquot** [comment]
This seems to have been resolved with the creation of `prices.prices_from_dex_data` as a replacement for `view_token_prices` especially after we applied @bh2smith's excellent patch #530.
