### ISSUE TITLE
Zeroex table missing

### ISSUE THREAD

**Issue by paulpierre** [duneanalytics/abstractions#523]
The table view "insert_weth_balance_changes" is querying the table zeroex."WETH9_evt_Withdrawal" but is unclear how this table is constructed?

**Comment by masquot** [comment]
Thank you @paulpierre. Great question. The table `zeroex."WETH9_evt_Withdrawal"` captures the `withdraw` events of the `WETH` smart contract: https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2. Agreed that it is confusing that the `WETH` contract lives under the `zeroex` namespace. We will fix this in our next major update.
