### ISSUE TITLE
WETH9 contains transfers from unrelated contract

### ISSUE THREAD

**Issue by paulpierre** [duneanalytics/abstractions#535]
Why does WETH9_evt_Transfer table contain transfers from the contract https://etherscan.io/address/0x14fbca95be7e99c15cc2996c6c9d841e54b79425#code

It does not seem related, is this a bug?

**Comment by paulpierre** [comment]
Is it possible to get the abstractions (table view SQL) for some of the baked in tables like:

```
async_art_v2."AsyncArtwork_v2_call_mintArtwork"

async."AsyncArtwork_call_mintArtwork"

async_art_v2."AsyncArtwork_v2_evt_Transfer"

erc20."ERC20_evt_Transfer"

gnosis_safe."Safev0.1.0_call_setup"

gnosis_safe."Safev1.0.0_call_setup"

gnosis_safe."Safev1.1.0_call_setup"

gnosis_safe."Safev1.1.1_call_setup"

zeroex_v2."Exchange2.1_evt_Fill"

oneinch."LimitOrderProtocol_call_fillOrder"

oneinch."LimitOrderProtocol_call_fillOrderRFQ"

onelp."Mooniswap_evt_Swapped"
```

**Comment by masquot** [comment]
> Why does WETH9_evt_Transfer table contain transfers from the contract https://etherscan.io/address/0x14fbca95be7e99c15cc2996c6c9d841e54b79425#code
> 
> It does not seem related, is this a bug?

Thank you for your comment. Could you please provide more specific info (what transfer exactly)  so we can investigate?

**Comment by masquot** [comment]
> Is it possible to get the abstractions (table view SQL) for some of the baked in tables like:
> 
> ```
> async_art_v2."AsyncArtwork_v2_call_mintArtwork"
> 
> async."AsyncArtwork_call_mintArtwork"
> 
> async_art_v2."AsyncArtwork_v2_evt_Transfer"
> 
> erc20."ERC20_evt_Transfer"
> 
> gnosis_safe."Safev0.1.0_call_setup"
> 
> gnosis_safe."Safev1.0.0_call_setup"
> 
> gnosis_safe."Safev1.1.0_call_setup"
> 
> gnosis_safe."Safev1.1.1_call_setup"
> 
> zeroex_v2."Exchange2.1_evt_Fill"
> 
> oneinch."LimitOrderProtocol_call_fillOrder"
> 
> oneinch."LimitOrderProtocol_call_fillOrderRFQ"
> 
> onelp."Mooniswap_evt_Swapped"
> ```

Sorry, I don't really get the question. Best place for questions is Dune's Discord channel: https://discord.gg/ErrzwBz

**Comment by masquot** [comment]
Glad to see you found you way to Dune's Discord! Closing here.
