### ISSUE TITLE
Some aToken Missing from ERC20

### ISSUE THREAD

**Issue by ABertoG** [duneanalytics/abstractions#94]
Hi 
Just spotted a few of Aave's aTokens are missing from the ERC20 list. 

If these can be added:
\\xfc1e690f61efd961294b3e1ce3313fbd8aa4f85d​ | aDAI | 18
\\x6ee0f7bb50a54ab5253da0667b0dc2ee526c30a8​ | aBUSD | 18
\\x712db54daa836b53ef1ecbb9c6ba3b9efb073f40​ | aENJ | 18
\\x69948cc03f478b95283f7dbf1ce764d0fc7ec54c​ | aREN | 18
\\x71010a9d003445ac60c4e6a7017c1e89a477b438​ | aREP | 18
\\x6fb0855c404e09c47c3fbca25f08d4e41f9f062f​ | aWBTC | 8
\\x6fb0855c404e09c47c3fbca25f08d4e41f9f062f​ | aZRX | 18

**Comment by hagaetc** [comment]
Hey @ABertoG please submit this as a pull request directly
