### ISSUE TITLE
Pause OP2 erc20.token_balances Cron

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/abstractions#972]
Hi, would we be able to temporarily truncate the[ `erc20.daily_token_balances`](https://github.com/duneanalytics/abstractions/blob/master/optimism2/erc20/daily_token_balances.sql) in the Optimism2 database and pause the [cron job](https://github.com/duneanalytics/abstractions/blob/master/optimism2/erc20/insert_daily_token_balances.sql)?

There are some issues with it that I need to resolve, so it's showing incorrect data right now.

**Comment by jeff-dude** [comment]
@MSilb7 cron job is paused & table is in process of being truncated
